"""add_checkpoint_columns

Revision ID: 0d4d49db1ed9
Revises: aa706e01ae19
Create Date: 2026-08-13 15:27:22.528684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4d49db1ed9'
down_revision: Union[str, None] = 'aa706e01ae19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_checkpoints', sa.Column('branch', sa.String(length=100), nullable=True))
    op.add_column('migration_checkpoints', sa.Column('repository_path', sa.String(length=1024), nullable=True))
    op.add_column('migration_checkpoints', sa.Column('repository_status', sa.Text(), nullable=True))
    op.add_column('migration_checkpoints', sa.Column('rollback_status', sa.String(length=50), nullable=False))
    op.add_column('migration_checkpoints', sa.Column('rollback_timestamp', sa.DateTime(), nullable=True))
    op.add_column('migration_checkpoints', sa.Column('rollback_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migration_checkpoints', 'rollback_error')
    op.drop_column('migration_checkpoints', 'rollback_timestamp')
    op.drop_column('migration_checkpoints', 'rollback_status')
    op.drop_column('migration_checkpoints', 'repository_status')
    op.drop_column('migration_checkpoints', 'repository_path')
    op.drop_column('migration_checkpoints', 'branch')
    # ### end Alembic commands ###
