"""initial_migration

Revision ID: 89fa6d9ced24
Revises: 
Create Date: 2026-08-13 14:59:23.454580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fa6d9ced24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('workspace_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('migration_plans',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('selected_capabilities', sa.JSON(), nullable=False),
    sa.Column('overall_risk', sa.String(length=50), nullable=False),
    sa.Column('dry_run_available', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('project_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=False),
    sa.Column('build_systems', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('databases', sa.JSON(), nullable=False),
    sa.Column('testing_frameworks', sa.JSON(), nullable=False),
    sa.Column('frontend_technologies', sa.JSON(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('is_multi_language', sa.Boolean(), nullable=False),
    sa.Column('raw_scan_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('migration_runs',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('changed_files', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('manual_remediation', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('output_bundle_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plans.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('build_results',
    sa.Column('build_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id')
    )
    op.create_table('migration_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_table('migration_errors',
    sa.Column('error_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_table('migration_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('migration_stages',
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('structured_results', sa.JSON(), nullable=True),
    sa.Column('error_information', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('recipe_executions',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=100), nullable=False),
    sa.Column('recipe_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('test_results',
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('recipe_executions')
    op.drop_table('migration_stages')
    op.drop_table('migration_reports')
    op.drop_table('migration_errors')
    op.drop_table('migration_checkpoints')
    op.drop_table('build_results')
    op.drop_table('migration_runs')
    op.drop_table('project_profiles')
    op.drop_table('migration_plans')
    op.drop_table('projects')
    # ### end Alembic commands ###
