"""add_stage_columns

Revision ID: aa706e01ae19
Revises: 89fa6d9ced24
Create Date: 2026-08-13 15:20:15.165573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa706e01ae19'
down_revision: Union[str, None] = '89fa6d9ced24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migration_stages', sa.Column('stage_order', sa.Integer(), nullable=False))
    op.add_column('migration_stages', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('migration_stages', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('migration_stages', sa.Column('message', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('migration_stages', 'message')
    op.drop_column('migration_stages', 'progress')
    op.drop_column('migration_stages', 'duration')
    op.drop_column('migration_stages', 'stage_order')
    # ### end Alembic commands ###
