"""
LLM-powered recipe recommendation endpoint.

POST /api/recipes/llm-recommend
  Body: same shape as /api/recipes/recommend
  Returns: { recommendations, reasoning, llm_powered, total }

When no LLM is configured, returns { llm_powered: false, recommendations: [] }
so the frontend can gracefully fall back to rule-based recommendations.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter
from pydantic import BaseModel, Field

from app.recipes.executor import get_executor_help, has_handler

logger = logging.getLogger(__name__)
router = APIRouter()


class LLMRecommendRequest(BaseModel):
    project_id: str = ""
    languages: List[str] = Field(default_factory=list)
    frameworks: List[str] = Field(default_factory=list)
    dependencies: List[Dict[str, Any]] = Field(default_factory=list)
    security_findings: List[Dict[str, Any]] = Field(default_factory=list)
    has_ci: bool = False
    has_tests: bool = False
    source_version: Optional[str] = None
    target_version: Optional[str] = None
    file_counts: Dict[str, int] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)


@router.post("/recipes/llm-recommend")
async def llm_recommend_recipes(req: LLMRecommendRequest):
    """
    Use the configured LLM (Gemini / OpenAI) to generate intelligent,
    project-specific recipe recommendations.

    Falls back to { llm_powered: false } when no LLM key is set.
    """
    from app.core.application.llm_service import get_llm_service
    from app.api.recipes import RECIPE_CATALOG

    llm = get_llm_service()

    if not llm.is_available:
        return {
            "llm_powered": False,
            "recommendations": [],
            "reasoning": (
                "LLM not configured. Add LLM_PROVIDER=gemini and GEMINI_API_KEY "
                "to backend/.env and restart the server."
            ),
            "total": 0,
        }

    # Build project profile to send to the LLM
    profile: Dict[str, Any] = {
        "languages": req.languages,
        "frameworks": req.frameworks,
        "has_ci": req.has_ci,
        "has_tests": req.has_tests,
        "source_version": req.source_version,
        "target_version": req.target_version,
        "file_counts": req.file_counts,
        "top_dependencies": [
            {"name": d.get("name"), "current": d.get("current_version"), "proposed": d.get("proposed_version")}
            for d in (req.dependencies or [])[:30]
        ],
        "security_findings": (req.security_findings or [])[:10],
        "metadata": req.metadata,
    }

    # Only expose recipes that have real executor handlers
    executable_ids = get_executor_help()  # sorted list of registered handler ids
    executable_set = set(executable_ids)
    available_recipes = [r for r in RECIPE_CATALOG if r["id"] in executable_set]

    recommendations = llm.recommend_recipes(profile, available_recipes, executable_ids)

    reasoning = (
        f"AI-powered recommendations generated by {llm.provider.capitalize()} "
        f"based on detected languages ({', '.join(req.languages) or 'none'}), "
        f"{len(req.dependencies)} dependencies, and {len(req.security_findings)} "
        f"security findings. {len(recommendations)} recipe(s) recommended."
    )

    return {
        "llm_powered": True,
        "provider": llm.provider,
        "recommendations": recommendations,
        "reasoning": reasoning,
        "total": len(recommendations),
    }


@router.get("/recipes/llm-status")
async def llm_status():
    """Returns the current LLM configuration status."""
    from app.core.application.llm_service import get_llm_service
    llm = get_llm_service()
    return {
        "llm_available": llm.is_available,
        "provider": llm.provider or "none",
        "executable_handlers": len(get_executor_help()),
    }
