import json
import sys
from pathlib import Path
from unittest.mock import patch
import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "backend"))

from app.recipes.executor import run_recipe
from app.core.domain.models import MigrationPlan, PlanStep, MigrationTarget, MigrationProfile
from app.core.orchestration.orchestrator import MigrationOrchestrator

@pytest.fixture(autouse=True)
def mock_dotnet_toolchain():
    import subprocess
    real_run = subprocess.run

    def conditional_run(cmd, *args, **kwargs):
        if not isinstance(cmd, list) or not cmd:
            return real_run(cmd, *args, **kwargs)
        
        cmd_str = " ".join(str(c) for c in cmd)
        if "RoslynTool.dll" in cmd_str:
            return real_run(cmd, *args, **kwargs)
        
        if str(cmd[0]) != "dotnet" or len(cmd) < 2:
            return real_run(cmd, *args, **kwargs)
        
        subcommand = str(cmd[1])
        proj_arg = " ".join(str(c) for c in cmd[2:])
        
        if "fail_build.csproj" in proj_arg:
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=1,
                stdout="Build failed. Error CS0103: The name 'xyz' does not exist in the current context.",
                stderr=""
            )
        else:
            if subcommand == "test":
                return subprocess.CompletedProcess(
                    args=cmd,
                    returncode=0,
                    stdout="Passed!  - Failed:     0, Passed:     3, Skipped:     0, Total:     3",
                    stderr=""
                )
            else:
                return subprocess.CompletedProcess(
                    args=cmd, returncode=0, stdout="Build succeeded.", stderr=""
                )

    with patch("shutil.which", return_value="mock_dotnet"),          patch("subprocess.run", side_effect=conditional_run):
        yield

# AForge-style C# file representing a real legacy source file with complex syntax constructs.
AFORGE_LEGACY_CS = """// <auto-generated />
// AForge Image Processing Library
// http://www.aforgenet.com/framework/
//
// Copyright © AForge.NET, 2005-2011
// contacts@aforgenet.com
//

using System;
using System.Diagnostics;

namespace AForge.Imaging.Filters
{
    /// <summary>
    /// Legacy AForge example processing filter mimicking real source constructs.
    /// </summary>
    [Serializable]
    [Obsolete("Use modern filters instead")]
    public class LegacyFilter
    {
        #region Fields & Properties
        private string filterName = "AForge Legacy Filter";
        public string FilterName
        {
            get { return this.filterName; }
        }
        #endregion

        #region Public Methods
        public void ProcessImage(byte[] pixelData)
        {
            // Inline comment inside method
            Debug.WriteLine("Processing image: " + this.FilterName);

            LegacyFilter.NestedHelper helper = new LegacyFilter.NestedHelper();
            string msg = helper.GetStatus();
            Console.WriteLine("Helper status: " + msg);
        }
        #endregion

        /// <summary>
        /// Nested helper class to test preservation of nested types.
        /// </summary>
        public class NestedHelper
        {
            public string GetStatus()
            {
                return "Ready";
            }
        }
    }
}
"""

AFORGE_CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
"""

def test_aforge_preservation_recipe_conversion(tmp_path: Path):
    cs_file = tmp_path / "LegacyFilter.cs"
    csproj_file = tmp_path / "AForge.Imaging.Filters.csproj"
    
    cs_file.write_text(AFORGE_LEGACY_CS, encoding="utf-8")
    csproj_file.write_text(AFORGE_CSPROJ, encoding="utf-8")
    
    # 1. Run cs-file-scoped-namespace recipe
    res_ns = run_recipe("cs-file-scoped-namespace", "ns-conv", str(tmp_path), dry_run=False)
    assert res_ns.status == "EXECUTED"
    
    final_cs = cs_file.read_text(encoding="utf-8")
    
    # Assert structural conversion worked
    assert "namespace AForge.Imaging.Filters;" in final_cs
    
    # Assert strict preservation of comments, regions, attributes, strings, nested classes, and members
    assert "// <auto-generated />" in final_cs
    assert "// AForge Image Processing Library" in final_cs
    assert "/// <summary>" in final_cs
    assert "[Serializable]" in final_cs
    assert '[Obsolete("Use modern filters instead")]' in final_cs
    assert '#region Fields & Properties' in final_cs
    assert 'private string filterName = "AForge Legacy Filter";' in final_cs
    assert 'Debug.WriteLine("Processing image: " + this.FilterName);' in final_cs
    assert 'LegacyFilter.NestedHelper helper = new LegacyFilter.NestedHelper();' in final_cs
    assert 'public class NestedHelper' in final_cs
    assert '#endregion' in final_cs


def test_aforge_preservation_recipe_rollback_on_failed_validation(tmp_path: Path):
    cs_file = tmp_path / "LegacyFilter.cs"
    csproj_file = tmp_path / "fail_build.csproj"  # triggers compile/validation failure
    
    cs_file.write_text(AFORGE_LEGACY_CS, encoding="utf-8")
    csproj_file.write_text(AFORGE_CSPROJ, encoding="utf-8")
    
    # Trigger recipe execution
    res = run_recipe("cs-file-scoped-namespace", "ns-conv", str(tmp_path), dry_run=False)
    
    # Assert execution fails
    assert res.status == "FAILED"
    assert res.success is False
    
    # Assert file was rolled back to its original legacy format
    final_cs = cs_file.read_text(encoding="utf-8")
    assert "namespace AForge.Imaging.Filters" in final_cs
    assert "{" in final_cs
    assert "namespace AForge.Imaging.Filters;" not in final_cs


def test_aforge_preservation_orchestrator_rollback_on_failed_validation(tmp_path: Path):
    cs_file = tmp_path / "LegacyFilter.cs"
    csproj_file = tmp_path / "fail_build.csproj"
    
    cs_file.write_text(AFORGE_LEGACY_CS, encoding="utf-8")
    csproj_file.write_text(AFORGE_CSPROJ, encoding="utf-8")
    
    step = PlanStep(
        step_id="step-1",
        order=1,
        name="C# Upgrade",
        description="Upgrade C# target framework",
        adapter="csharp",
        capability="csharp-roslyn-ast"
    )
    plan = MigrationPlan(
        plan_id="plan-aforge",
        project_id="proj-aforge",
        profile=MigrationProfile.CONSERVATIVE,
        targets=[MigrationTarget(language="csharp", target_version="net8.0")],
        steps=[step],
    )
    
    orchestrator = MigrationOrchestrator()
    result = orchestrator.migrate(str(tmp_path), plan)
    
    # Assert validation failed status propagates
    assert result.status.value == "FAILED"
    
    # Assert original content was restored
    final_cs = cs_file.read_text(encoding="utf-8")
    assert "namespace AForge.Imaging.Filters" in final_cs
    assert "{" in final_cs
    assert "namespace AForge.Imaging.Filters;" not in final_cs

# ── Regression Tests for Code Cleanup & Optimization Stage ───────────────────────

def test_aforge_optimization_and_cleanup_preservation(tmp_path: Path):
    from app.optimization.optimizer import CodeOptimizer, _make_unified_diff
    from app.core.domain.models import FileChangeMetadata

    # Setup source file and project file mimicking AForge legacy structure
    cs_file = tmp_path / "LegacyFilter.cs"
    csproj_file = tmp_path / "AForge.Imaging.Filters.csproj"
    
    cs_file.write_text(AFORGE_LEGACY_CS, encoding="utf-8")
    csproj_file.write_text(AFORGE_CSPROJ, encoding="utf-8")

    # 1. Run modernization recipe (namespace upgrade)
    res_ns = run_recipe("cs-file-scoped-namespace", "ns-conv", str(tmp_path), dry_run=False)
    assert res_ns.status == "EXECUTED"
    
    modernized_content = cs_file.read_text(encoding="utf-8")
    assert "namespace AForge.Imaging.Filters;" in modernized_content
    
    # Check that comments, regions, member-access before optimization are correct
    assert "// Inline comment inside method" in modernized_content
    assert "#region Fields & Properties" in modernized_content
    assert "LegacyFilter.NestedHelper helper" in modernized_content

    # 2. Run CodeOptimizer on the modernized file
    optimizer = CodeOptimizer()
    
    # Create FileChangeMetadata representing the modernization result
    item = FileChangeMetadata(
        file="LegacyFilter.cs",
        status="MODIFIED",
        before_content=AFORGE_LEGACY_CS,
        after_content=modernized_content,
        diff=_make_unified_diff(AFORGE_LEGACY_CS, modernized_content, "LegacyFilter.cs")
    )
    
    # Run optimizer in apply mode
    opt_result = optimizer.optimize(str(tmp_path), [item], dry_run=False)
    
    assert opt_result.success is True
    assert opt_result.rolled_back is False
    assert opt_result.build_passed is True

    # 3. Verify optimized content preserves all requested properties
    optimized_content = cs_file.read_text(encoding="utf-8")
    
    # Modernization namespace change must remain intact
    assert "namespace AForge.Imaging.Filters;" in optimized_content
    
    # Comments, strings, and attributes must be preserved
    assert "// <auto-generated />" in optimized_content
    assert "// AForge Image Processing Library" in optimized_content
    assert "// Inline comment inside method" in optimized_content
    assert "[Serializable]" in optimized_content
    assert '[Obsolete("Use modern filters instead")]' in optimized_content
    assert 'private string filterName = "AForge Legacy Filter";' in optimized_content
    assert 'Debug.WriteLine("Processing image: " + this.FilterName);' in optimized_content
    
    # Regions must be preserved
    assert "#region Fields & Properties" in optimized_content
    assert "#region Public Methods" in optimized_content
    assert "#endregion" in optimized_content
    
    # Member access . must be preserved
    assert "LegacyFilter.NestedHelper helper = new LegacyFilter.NestedHelper();" in optimized_content
    assert "string msg = helper.GetStatus();" in optimized_content

    # Traceability diffs verification
    opt_file = opt_result.optimized_files[0]
    assert opt_file.original_content == AFORGE_LEGACY_CS
    assert opt_file.modernized_content == modernized_content
    assert opt_file.optimized_content == optimized_content
    
    # Diffs must be real and non-empty for modernization
    assert "namespace AForge.Imaging.Filters;" in opt_file.modernization_diff
    # Optimization diff represents format changes (e.g. dotnet format removing block brace)
    if opt_file.changed:
        assert opt_file.optimization_diff != ""
        assert "a/LegacyFilter.cs" in opt_file.final_diff
    else:
        assert opt_file.optimization_diff == ""


def test_aforge_optimization_rollback_independent_of_modernization(tmp_path: Path):
    from app.optimization.optimizer import CodeOptimizer, _make_unified_diff
    from app.core.domain.models import FileChangeMetadata

    cs_file = tmp_path / "LegacyFilter.cs"
    csproj_file = tmp_path / "fail_build.csproj"  # triggers validation/build failure after optimization
    
    cs_file.write_text(AFORGE_LEGACY_CS, encoding="utf-8")
    csproj_file.write_text(AFORGE_CSPROJ, encoding="utf-8")

    # 1. Run modernization recipe (namespace upgrade) with normal csproj first so it passes
    # We rename csproj temporarily to let recipe execution pass validation
    normal_csproj = tmp_path / "AForge.Imaging.Filters.csproj"
    normal_csproj.write_text(AFORGE_CSPROJ, encoding="utf-8")
    
    res_ns = run_recipe("cs-file-scoped-namespace", "ns-conv", str(tmp_path), dry_run=False)
    assert res_ns.status == "EXECUTED"
    modernized_content = cs_file.read_text(encoding="utf-8")
    
    # Remove normal csproj to activate fail_build.csproj
    normal_csproj.unlink()
    
    # 2. Run CodeOptimizer. The dotnet build will fail because of fail_build.csproj
    optimizer = CodeOptimizer()
    item = FileChangeMetadata(
        file="LegacyFilter.cs",
        status="MODIFIED",
        before_content=AFORGE_LEGACY_CS,
        after_content=modernized_content,
        diff=""
    )
    
    opt_result = optimizer.optimize(str(tmp_path), [item], dry_run=False)
    
    # Assert optimization failed and was rolled back
    assert opt_result.success is False
    assert opt_result.rolled_back is True
    assert opt_result.build_passed is False
    
    # Assert optimization rollback is independent: modernized namespace content remains intact,
    # but the optimized formatter changes were rolled back!
    current_content = cs_file.read_text(encoding="utf-8")
    assert "namespace AForge.Imaging.Filters;" in current_content, (
        "Modernization changes (file-scoped namespace) must remain intact after optimization rollback"
    )


def test_aforge_optimization_skips_generated_file(tmp_path: Path):
    from app.optimization.optimizer import CodeOptimizer, _make_unified_diff
    
    gen_file = tmp_path / "Form1.Designer.cs"
    gen_file.write_text(AFORGE_LEGACY_CS, encoding="utf-8")
    
    optimizer = CodeOptimizer()
    result = optimizer.optimize(str(tmp_path), ["Form1.Designer.cs"], dry_run=False)
    
    assert result.files_skipped == 1
    assert len(result.optimized_files) == 0
    assert result.skipped_files[0].file == "Form1.Designer.cs"
    assert "generated" in result.skipped_files[0].reason.lower()
